### ISSUE TITLE
No longer loads on core-2021.6.0

### ISSUE THREAD

**Issue by howlermonkeys** [csacca/uhoo-homeassistant#2]
after core-2021.6.0, existing integrations no longer load on start, and the integration is no longer visible in the integration list after this repo is installed via HACS

**Comment by howlermonkeys** [comment]
[homeassistant.loader] The custom integration 'uhoo' does not have a valid version key (None) in the manifest file and was blocked from loading. See https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes#versions for more details

**Comment by csacca** [comment]
This issue was resolved with release 0.0.3
